version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./server
        target: /app
    tty: true
