name: Branch Restrictions

on:
  pull_request:
    branches:
      - main

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from a branch with 'develop' in its name
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ ! "$BRANCH" == *develop* ]]; then
            echo "Error: PRs to main must come from a branch that includes 'develop' in its name."
            exit 1
          fi
